services:
  bot:
    build:
      context: .
      target: dev
    command: pnpm dev
    environment:
      NODE_ENV: development
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      API_URL: ${API_URL}
    networks:
      - internal
    depends_on:
      - db
      - api
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json

  api:
    build:
      context: ../saint-cochon-api
      target: dev
    command: pnpm dev
    ports:
      - "3000:3000"
    env_file: ../saint-cochon-api/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/saint-cochon
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_TOKEN}
      ALLOWED_ORIGINS: "http://localhost:5173"
    networks:
      - internal
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ../saint-cochon-api/src
          target: /app/src
        - action: rebuild
          path: ../saint-cochon-api/package.json

  webapp:
    build:
      context: ../saint-cochon-webapp
      target: dev
    command: pnpm dev --host
    ports:
      - "5173:5173"
    env_file: ../saint-cochon-webapp/.env
    networks:
      - web
    develop:
      watch:
        - action: sync
          path: ../saint-cochon-webapp/src
          target: /app/src
        - action: rebuild
          path: ../saint-cochon-webapp/package.json