name: Deploy Bot to Production

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Connect and deploy to server
              uses: appleboy/ssh-action@master
              env:
                ENV_FILE: ${{ secrets.ENV_FILE }}
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                script: |
                  cd /home/ubuntu/saint-cochon-bot
                  git pull origin main
                  echo "$ENV_FILE" > .env
                  docker compose -f compose/yaml -f compose.prod.yaml up -d --build bot